CDIR=${.CURDIR}/../../../target/musl/src
LIB=		c
SHLIB=		c
SHLIB_MAJOR=	0
DIR=		/lib
SHLIBDIR=	${DIR}
LIBDIR=		${DIR}
SUBDIR=		aio ctype exit ipc locale mman passwd sched signal string time \
		complex dirent fcntl ldso malloc mq prng search stat temp \
		unistd conf env fenv legacy math multibyte process select \
		stdio termios crypt errno internal linux misc network regex \
		setjmp stdlib thread 
#SRCS = src/*/*.c

#INCS = include/*.h
#OBJS = $(SRCS:.c=.o)
#LOBJS = $(OBJS:.o=.lo)
#OBJS = /src/*/*.o
#LOBJS = src/*/*.o

.include <bsd.lib.mk>
#.include <bsd.subdir.mk>
